const http=async(u,ref)=>{const{Http}=await import('@capacitor-community/http');const r=await Http.get({url:u,connectTimeout:8000,readTimeout:8000,headers:{'Referer':ref||'https://fund.eastmoney.com/','User-Agent':'Mozilla/5.0 (Linux; Android 14)'}});return typeof r.data==='string'?r.data:''}
const sj=t=>{try{return JSON.parse(t.replace(/NaN/g,'null').replace(/Infinity/g,'null'))}catch(e){console.log('JSON parse error:',(t||'').slice(0,50));return null}}

export async function fetchFundNAV(code,days=90){try{const t=await http('http://fund.eastmoney.com/pingzhongdata/'+code+'.js','https://fund.eastmoney.com/');const nm=t.match(/Data_netWorthTrend\s*=\s*(\[[\s\S]*?\])/);if(!nm){console.log('NAV regex fail:',code,t.slice(0,80));return[]}const nd=sj(nm[1]);if(!nd)return[];const am=t.match(/Data_ACWorthTrend\s*=\s*(\[[\s\S]*?\])/);let amap={};if(am){(sj(am[1])||[]).forEach(a=>{if(Array.isArray(a))amap[a[0]]=a[1];else if(a?.x)amap[a.x]=a.y})};const c=Date.now()-days*86400000;const r=[];nd.forEach(n=>{if(n.x>=c)r.push({date:new Date(n.x).toISOString().slice(0,10),nav:+n.y.toFixed(4),acc_nav:+(amap[n.x]||0).toFixed(4),daily_return:0})});for(let i=1;i<r.length;i++)if(r[i-1].nav>0)r[i].daily_return=+((r[i].nav-r[i-1].nav)/r[i-1].nav*100).toFixed(2);return r.slice(-days)}catch(e){console.log('NAV error:',code,e.message);return[]}}

export async function fetchIndices(){const n={'000001':'上证指数','399001':'深证成指','399006':'创业板指','000688':'科创50','000300':'沪深300','000905':'中证500','000852':'中证1000','399005':'中小100'};try{const t=await http('http://push2.eastmoney.com/api/qt/ulist.np/get?fltt=2&secids=1.000001,0.399001,0.399006,1.000688,1.000300,1.000905,1.000852,0.399005&fields=f2,f3,f4,f5,f6,f12,f14,f15,f16,f17,f18','https://quote.eastmoney.com/');const d=sj(t);if(d?.data?.diff)return d.data.diff.map(i=>({code:i.f12,name:n[i.f12]||i.f14,price:+i.f2?.toFixed(2)||0,change_pct:+i.f3?.toFixed(2)||0,change_amt:+i.f4?.toFixed(2)||0,volume:i.f5||0,high:+i.f15?.toFixed(2)||0,low:+i.f16?.toFixed(2)||0,open:+i.f17?.toFixed(2)||0,prev_close:+i.f18?.toFixed(2)||0}))}catch(e){console.log('Indices error:',e.message)}return[]}

export async function fetchSectors(){try{const t=await http('http://push2.eastmoney.com/api/qt/clist/get?pn=1&pz=30&po=1&np=1&fltt=2&invt=2&fid=f3&fs=m:90+t:2&fields=f2,f3,f12,f14','https://quote.eastmoney.com/');const d=sj(t);if(d?.data?.diff)return d.data.diff.map(i=>({code:i.f12,name:i.f14,price:+i.f2?.toFixed(2)||0,change_pct:+i.f3?.toFixed(2)||0}))}catch(e){console.log('Sectors error:',e.message)}return[]}

let fl=null
export async function searchFunds(q){try{if(!fl){const t=await http('http://fund.eastmoney.com/js/fundcode_search.js','https://fund.eastmoney.com/');const m=t.match(/var\s+r\s*=\s*(\[\[[\s\S]*?\]\]);/);if(m)fl=sj(m[1])||[]}if(!fl)return[];const ql=q.toLowerCase();return fl.filter(i=>i[0].includes(ql)||(i[2]||'').toLowerCase().includes(ql)).slice(0,20).map(i=>({fund_code:i[0],fund_name:i[2],fund_type:i[3]||''}))}catch{return[]}}
